name: location_tracker
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4



dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  permission_handler: ^11.4.0  
  geolocator: ^13.0.2        
  flutter_local_notifications: ^18.0.1  
  shared_preferences: ^2.5.2 
  flutter_riverpod: ^2.4.9   
  flutter_screenutil: ^5.9.0 


  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.12
  flutter_font_icons: ^2.2.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  web:
    generate: true  


  image_path: "assets/3d-map.png"  
  adaptive_icon_foreground: "assets/3d-map.png" 
  adaptive_icon_background: "#ffffff"  
